services:
  shop-interface-nginx:
    image: nginx
    ports:
      - 7000:80
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/logs:/var/log/nginx

  shop-interface-redis-server:
    image: redis
    ports:
      - 6379:6379
    restart: always

  shop-interface-mongo:
    image: mongo
    prots:
      - 27027:27027
    restart: always

  shop-interface:
    build: ./
    volumes:
      - ./:/usr/local/app
    restart: always
    working_dir: /usr/local/app
    command: npm start
    ports:
      - 7001:7001
    depends_on:
      - shop-interface
    links:
      - shop-interface-redis-server:rd
      - shop-interface-mongo:mg
