version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 7000:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /tmp/logs:/var/log/nginx

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo:/data/db

  app:
    build: ./
    volumes:
      - ./:/usr/local/app
    restart: always
    working_dir: /usr/local/app
    command: npm start
    ports:
      - 7001:7001
    depends_on:
      - shop-interface
    links:
      - redis:rd
      - mongo:mg
